platform:ios,'7.0'
pod "AFNetworking", "~> 2.5.3"
pod "MBProgressHUD", "~> 0.9.1"
pod 'MagicalRecord', '~> 2.3.0'
pod "RDVTabBarController", "~> 1.1.9"
pod "EaseMobSDK", "~> 2.1.6"
pod "SVProgressHUD"
pod "IHKeyboardAvoiding", "~>2.4"
pod "SWTableViewCell", "~>0.3.7"


